#!/bin/sh
set -e

if [[ -n "$1" ]]; then
    nix-build ./nix/default.nix
    cp -f ./result/bin/xmonad "$1"
else
    nix-env -f ~/.dots/nixpkgs/pkgs/top-level/all-packages.nix -iA xmonad
    echo "./build: no copy arguments given, leaving in ./result/"
fi

