resolver: lts-16.3

nix:
  packages:
    - x11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - haskellPackages.xmonad
    - haskellPackages.xmonad-contrib
    - haskellPackages.xmonad-extras
    - pkgconfig

packages: [ . ]

extra-deps:
- alsa-0.4
- array-0.3.0.3
