---
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos
      - run: nix-build ./nix/default.nix
      - uses: actions/upload-artifact@v1
        with:
          name: xmonad-${{ runner.os }}
          path: package
