---
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          skip_adding_nixpkgs_channel: true
          # install_url:
      - run: nix-build
      - uses: actions/upload-artifact@v1
        with:
          name: xmonad-${{ runner.os }}
          path: package
