---
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-20.03
      - run: nix-build ./nix/default.nix
      - uses: actions/upload-artifact@v1
        with:
          name: xmonad-${{ runner.os }}
          path: package

      # TODO: use haskell.nix
      # https://gist.github.com/domenkozar/42311c302da74c10089a8ac28afd7bbc
      # - uses: cachix/install-nix-action@v10
      #   with:
      #     skip_adding_nixpkgs_channel: true
      # - uses: cachix/cachix-action@v6
      #   with:
      #     name: mycache
      #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      # - run: cachix use iohk
      # - run: nix-build -A mypackage.components.all
